FROM golang@sha256:c8e89fb596994c4efd19f73d9536fd60f539726d087881f9a71a9f376882f24e

COPY ./server /go/src/github.com/envoyproxy/envoy/example/load-reporting-service/server
COPY *.go /go/src/github.com/envoyproxy/envoy/example/load-reporting-service/
COPY go.sum /go/src/github.com/envoyproxy/envoy/example/load-reporting-service
COPY go.mod /go/src/github.com/envoyproxy/envoy/example/load-reporting-service

WORKDIR /go/src/github.com/envoyproxy/envoy/example/load-reporting-service
RUN go mod download
RUN go install /go/src/github.com/envoyproxy/envoy/example/load-reporting-service

CMD ["go","run","main.go"]
